name: Build and Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build the JupyterLite site
        env:
          PYODIDE_CDN_URL: https://xiaoshuai-static.oss-accelerate.aliyuncs.com/pyodide/v0.20.0/full/pyodide.js
          # JUPYTERLITE_PYODIDE_URL: https://xiaoshuai-static.oss-accelerate.aliyuncs.com/pyodide/v0.20.0/full/pyodide.js
          # JUPYTERLITE_BASE_URL: https://xiaoshuai-static.oss-accelerate.aliyuncs.com/jupyterlite-play/
        run: |
          cp README.md content
          # echo $JUPYTERLITE_PYODIDE_URL $JUPYTERLITE_BASE_URL
          jupyter lite build --contents content
          rm -f _output/lab/favicon.ico
          cp favicon.ico _output/lab/
          touch _output/.nojekll
          echo play.xiaoshu.ai > _output/CNAME
      - name: Upload (dist)
        uses: actions/upload-artifact@v2
        with:
          name: jupyterlite-demo-dist-${{ github.run_number }}
          path: ./_output

  deploy:
    if: github.ref == 'refs/heads/dev'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - uses: actions/download-artifact@v2
        with:
          name: jupyterlite-demo-dist-${{ github.run_number }}
          path: ./dist
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: dist
        # uses: peaceiris/actions-gh-pages@v3
        # if: github.ref == 'refs/heads/dev'
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   publish_dir: ./dist
        #   cname: play.xiaoshu.ai
